api_keys:
  openrouter: INSERT_TEST_API_KEY_HERE
models:
  claude-3-opus:
    max_tokens: 4096
    model_id: anthropic/claude-3-opus
    provider: openrouter
    temperature: 0.7
strategies:
  progressive_deep_dive:
    confidence_threshold: 0.8
    max_depth: 3
